# MANAGED BY CHEZMOI! EDIT ONLY WITH: chezmoi edit

[tools]
node = "latest"
python = "latest"
go = "latest"
rust = "latest"
uv = "latest"
bun = "latest"

[settings]
verbose = false
yes = true
experimental = true
disable_backends = ["asdf"]

[hooks]
# automatically run `mise i` when entering a project with mise.toml
enter = "mise i -q"
