# MANAGED BY CHEZMOI! EDIT ONLY WITH: chezmoi edit

[tools]
node = "lts"
python = "latest"
go = "latest"
rust = "stable"

[settings]
verbose = false
yes = true
experimental = true

[hooks]
# automatically run `mise i` when entering a project with mise.toml
enter = "mise i -q"
